#ifndef TP_SYS_H
# define TP_SYS_H

# include <stddef.h>

/* ============================================================
 * Transparent mode, system side (Linux only): the nftables helper
 * (src/transparent/nft.c) and the `dpi-proxy --mode transparent`
 * entry point (src/transparent/transparent.c). The pure decision
 * logic lives in tp.h.
 * ============================================================ */

/* nft.c — every function runs `nft -f -` with text generated by
 * tp.h's builders; only table inet TP_NFT_TABLE is ever touched. */
int		tp_nft_run(const char *text, size_t len, int quiet);
/* (Re)creates the whole table atomically, then arms the heartbeat.
 * dns_port 0: DNS is not redirected. */
int		tp_nft_install(int port, int ipv6, int dns_port);
/* Heartbeat: re-arms the alive set (fail-open timer). */
int		tp_nft_refresh(void);
/* Idempotent; a missing table is not an error. */
void	tp_nft_remove(void);
void	tp_nft_flush_quic(void);
int		tp_nft_add_quic(int family, const char *addr);

typedef struct s_tp_options
{
	int			port;				/* loopback listener port */
	int			debug;				/* per-connection log lines */
	const char	*strategy_conf;		/* manual rules (strategy.conf) */
	const char	*decisions_file;	/* learned decisions */
	const char	*status_file;		/* for `dpi-proxy-ctl status` */
	const char	*dns_servers;		/* plain-DNS fallback: IP literals */
	/* local DNS forwarder: 0 = don't intercept DNS at all */
	int			dns_port;
	/* resolve over DNS-over-HTTPS (1.1.1.1, 8.8.8.8, 9.9.9.9) first,
	 * plain UDP only when every DoH server failed; 0 = UDP only */
	int			doh;
}	t_tp_options;

/* Fills defaults, then applies DPI_PROXY_* environment overrides. */
void	tp_options_default(t_tp_options *opt);

/* Runs until SIGTERM/SIGINT; removes the nftables table on the way
 * out. Returns 0 on a clean stop, -1 if startup failed. */
int		run_transparent_server(const t_tp_options *opt);

#endif
